# Generated by Django 4.2.7 on 2023-11-22 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=100)),
                ('field_two', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_three', models.CharField(max_length=100)),
                ('field_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.firstmodel')),
            ],
        ),
    ]
