# Generated by Django 4.2.7 on 2023-11-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_firstmodel_secondmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondmodel',
            name='field_four',
        ),
        migrations.DeleteModel(
            name='FirstModel',
        ),
        migrations.DeleteModel(
            name='SecondModel',
        ),
    ]
