# Generated by Django 4.2.7 on 2023-11-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_firstmodel_secondmodel_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondmodel',
            name='first_model',
        ),
        migrations.DeleteModel(
            name='FirstModel',
        ),
        migrations.DeleteModel(
            name='SecondModel',
        ),
    ]
